# THIS FILE IS AUTOGENERATED USING `mix ash.formatter`
# DONT MODIFY IT BY HAND
locals_without_parens = [
  access_type: 1,
  authorize_if: 1,
  authorize_if: 2,
  authorize_unless: 1,
  authorize_unless: 2,
  forbid_if: 1,
  forbid_if: 2,
  forbid_unless: 1,
  forbid_unless: 2,
  name: 1,
  policy: 1,
  policy: 2
]

[
  inputs: ["{mix,.formatter}.exs", "{config,lib,test}/**/*.{ex,exs}"],
  locals_without_parens: locals_without_parens,
  export: [
    locals_without_parens: locals_without_parens
  ]
]
